# -*- coding: utf-8 -*-
"""Programa_5_diccionarios_MIO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ab663qyDFuS7yVogyCh7ztrGjLqjEupn
"""

class Persona:
    def __init__(self):
        # Diccionario con los datos personales
        self.datos = {
            "Nombre": "Juan Pérez",
            "Matricula": "A001",
            "Edad": 18,
            "Peso": 70,
            "Telefono": "555-123-456",
            "Domicilio": "Calle Falsa 123",
            "Carrera": "Ingeniería en Sistemas"
        }

    # Método para mostrar todos los datos
    def mostrar_datos(self):
        print("\n=== Datos Personales ===")
        for clave, valor in self.datos.items():
            print(clave, ":", valor)

    # Método para obtener un dato específico
    def obtener_dato(self, clave):
        return self.datos.get(clave, "Ese dato no existe")

    # Método para modificar un dato
    def modificar_dato(self, clave, nuevo_valor):
        if clave in self.datos:
            self.datos[clave] = nuevo_valor
            print(f"{clave} actualizado a: {nuevo_valor}")
        else:
            print("La clave no existe en el diccionario")


# Creamos un objeto de tipo Persona
persona1 = Persona()

# Mostrar todos los datos
persona1.mostrar_datos()

# Acceder a un dato
print("\nNombre:", persona1.obtener_dato("Nombre"))

# Modificar un dato
persona1.modificar_dato("Edad", 19)

# Mostrar de nuevo los datos para ver el cambio
persona1.mostrar_datos()
