# -*- coding: utf-8 -*-
"""Programa_6_Operaciones_con_listas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eh8xO-z7EjdvSDCk800UxisuNpVmDITu
"""

# Fórmula: °C = (°F - 32) * 5/9
class EstacionMeteorologica:
    def __init__(self):
        # Lista de temperaturas en Fahrenheit
        self.temp_f = [80, 72, 95, 82, 79, 72, 85]

    # Método para mostrar las temperaturas en F
    def mostrar_fahrenheit(self):
        print("\nTemperaturas en Fahrenheit:")
        for t in self.temp_f:
            print(t, "°F")

    # Método para convertir a centígrados
    def convertir_a_centigrados(self):
        temp_c = []
        for t in self.temp_f:
            c = (t - 32) * 5/9  # fórmula
            temp_c.append(round(c, 2))  # redondear a 2 decimales
        return temp_c

    # Método para mostrar las temperaturas en C
    def mostrar_centigrados(self):
        print("\nTemperaturas en Centígrados:")
        for c in self.convertir_a_centigrados():
            print(c, "°C")


estacion = EstacionMeteorologica()

# Mostrar lista original
estacion.mostrar_fahrenheit()

# Mostrar lista convertida
estacion.mostrar_centigrados()